version: '3.4'

services:
  app:
    build: .
    working_dir: /ingilizce-kelime-go
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    volumes:
      - ./healthchecks:/healthchecks
      - ./config/redis.conf:/usr/local/etc/redis.conf
    ports:
      - "0.0.0.0:6379:6379"
    entrypoint:
      - redis-server
      - /usr/local/etc/redis.conf
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "10s"
